const logEl=document.getElementById("log");
const x_super_properties='eyJvcyI6IldpbmRvd3MiLCJicm93c2VyIjoiQ2hyb21lIiwiZGV2aWNlIjoiIiwic3lzdGVtX2xvY2FsZSI6ImVuLVVTIiwiaGFzX2NsaWVudF9tb2RzIjpmYWxzZSwiYnJvd3Nlcl91c2VyX2FnZW50IjoiTW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzNC4wLjAuMCBTYWZhcmkvNTM3LjM2IiwiYnJvd3Nlcl92ZXJzaW9uIjoiMTM0LjAuMC4wIiwib3NfdmVyc2lvbiI6IjEwIiwicmVmZXJyZXIiOiJodHRwczovL2Rpc2NvcmQuY29tIiwicmVmZXJyaW5nX2RvbWFpbiI6ImRpc2NvcmQuY29tIiwicmVmZXJyZXJfY3VycmVudCI6IiIsInJlZmVycmluZ19kb21haW5fY3VycmVudCI6IiIsInJlbGVhc2VfY2hhbm5lbCI6InN0YWJsZSIsImNsaWVudF9idWlsZF9udW1iZXIiOjM4NDg4NywiY2xpZW50X2V2ZW50X3NvdXJjZSI6bnVsbH0=';
let shouldStopSpam=!1;
const tokensInput=document.getElementById('tokens'),guildInput=document.getElementById('guildId'),channelInput=document.getElementById('channelIds'),messageInput=document.getElementById('message'),randomizeCheckbox=document.getElementById('randomize'),delayInput=document.getElementById('delay'),limitInput=document.getElementById('limit'),mentionInput=document.getElementById('mentionIds'),pollTitleInput=document.getElementById('pollTitle'),pollAnswersInput=document.getElementById('pollAnswers'),forwardUrlInput=document.getElementById('forwardMessageUrl'),autoFillBtn=document.getElementById('autoFillChannels'),fetchMentionsBtn=document.getElementById('fetchMentions'),submitBtn=document.getElementById('submitBtn'),stopBtn=document.getElementById('stopSpam'),leaveBtn=document.getElementById('leaveBtn'),form=document.getElementById('form');
function appendLog(t){const n=new Date().toLocaleTimeString();logEl.textContent+=`\n${n} - ${t}`,logEl.scrollTop=logEl.scrollHeight}function clearLog(){logEl.textContent=''}function sleep(t){return new Promise(e=>setTimeout(e,t))}function parseList(t){return[...new Set(t.split(/[\s,]+/).map(t=>t.trim()).filter(t=>t))]}function parseMessageUrl(t){if(!t)return null;const e=t.match(/https:\/\/discord\.com\/channels\/(\d+)\/(\d+)\/(\d+)/);return e?{guildId:e[1],channelId:e[2],messageId:e[3]}:null}
async function leaveGuild(t,e){const n=await fetch(`https://discord.com/api/v9/users/@me/guilds/${e}`,{method:"DELETE",headers:{Authorization:t,"Content-Type":"application/json","x-super-properties":x_super_properties},body:JSON.stringify({lurking:!1}),referrerPolicy:"no-referrer"});n.status===204?appendLog(`Success: ${t.slice(0,10)}...`):appendLog(`Failed: ${t.slice(0,10)}...`)}
autoFillBtn.onclick=async()=>{clearLog();const t=parseList(tokensInput.value),e=guildInput.value.trim();if(!t.length)return appendLog("Warning: トークンを入力");if(!e)return appendLog("Warning: サーバーIDを入力");try{const n=await fetch(`https://discord.com/api/v9/guilds/${e}/channels`,{headers:{Authorization:t[0],"Content-Type":"application/json","x-super-properties":x_super_properties}});if(!n.ok)throw new Error();const o=(await n.json()).filter(t=>t.type===0).map(t=>t.id);channelInput.value=o.join(","),appendLog("Success: チャンネル取得完了")}catch(t){appendLog("Failed: チャンネル取得エラー")}}
fetchMentionsBtn.onclick=async()=>{clearLog();const t=parseList(tokensInput.value),e=guildInput.value.trim(),n=parseList(channelInput.value);if(!t.length||!e||!n.length)return appendLog("Warning: 必要項目を入力");const o=new WebSocket("wss://gateway.discord.gg/?v=9&encoding=json");o.onopen=()=>{o.send(JSON.stringify({op:2,d:{token:t[0],properties:{os:"Windows",browser:"Discord",device:"pc"},intents:1<<12}}))};o.onmessage=s=>{const a=JSON.parse(s.data);if(a.op===0&&a.t==="READY")o.send(JSON.stringify({op:14,d:{guild_id:e,typing:!0,activities:!0,threads:!0,channels:{[n[0]]:[[0,100]]}}}));if(a.t==="="GUILD_MEMBER_LIST_UPDATE"){const t=a.d.ops[0].items.filter(t=>t.member).map(t=>t.member.user.id);t.length?(mentionInput.value=t.join(","),appendLog("Success: メンション取得完了")):appendLog("メンションなし"),o.close()}};o.onerror=()=>{appendLog("Error: WebSocketエラー"),o.close()}}
async function sendMessage(t,e,n,o={}){let s={content:n||""};o.randomize&&(s.content+="\n"+crypto.randomUUID());if(o.randomMentions){const n=o.randomMentions[Math.floor(Math.random()*o.randomMentions.length)];s.content=`<@${n}>\n`+s.content}if(o.pollTitle&&o.pollAnswers)s.poll={question:{text:o.pollTitle},answers:o.pollAnswers.map(t=>({poll_media:{text:t.trim()}})),allow_multiselect:!1,duration:1,layout_type:1};return await fetch(`https://discord.com/api/v9/channels/${e}/messages`,{method:"POST",headers:{Authorization:t,"Content-Type":"application/json","x-super-properties":x_super_properties},body:JSON.stringify(s),referrerPolicy:"no-referrer"})}
async function forwardMessage(t,e,n){const o={content:"",message_reference:{guild_id:n.guildId,channel_id:n.channelId,message_id:n.messageId,type:1}};return await fetch(`https://discord.com/api/v9/channels/${e}/messages`,{method:"POST",headers:{Authorization:t,"Content-Type":"application/json","x-super-properties":x_super_properties},body:JSON.stringify(o),referrerPolicy:"no-referrer"})}
async function sendMessageWithRetry(t,e,n,o={},s=5,a=1500){for(let r=0;r<s;r++)try{const i=await sendMessage(t,e,n,o);if(i.ok)return appendLog(`Success: ${t.slice(0,10)}...`),!0;if(i.status===429){const t=await i.json(),e=(t.retry_after||1)*1000;appendLog(`Rate limit: ${e/1000}s`),await sleep(e)}else if(i.status===401)return appendLog(`Failed: ${t.slice(0,10)}...`),!1}catch(t){await sleep(a)}return!1}
async function forwardMessageWithRetry(t,e,n,o=5,s=1500){for(let a=0;a<o;a++)try{const r=await forwardMessage(t,e,n);if(r.ok)return appendLog(`Success: ${t.slice(0,10)}...`),!0;if(r.status===429){const t=await r.json(),e=(t.retry_after||1)*1000;appendLog(`Rate limit: ${e/1000}s`),await sleep(e)}}catch(t){await sleep(s)}return!1}
function checkFormValidity(){const t=!!tokensInput.value.trim()&&!!guildInput.value.trim(),e=!!messageInput.value.trim()||!!forwardUrlInput.value.trim();submitBtn.disabled=!(t&&e)}
["tokens","guildId","message","forwardMessageUrl"].forEach(t=>document.getElementById(t).addEventListener("input",checkFormValidity));checkFormValidity();
form.onsubmit=async t=>{t.preventDefault();const e=messageInput.value.trim(),n=forwardUrlInput.value.trim();if(!e&&!n)return appendLog("Warning: 内容を入力");submitBtn.disabled=!0,submitBtn.classList.add("loading"),submitBtn.textContent="実行中...",shouldStopSpam=!1,stopBtn.disabled=!1;const o=parseList(tokensInput.value),s=guildInput.value.trim(),a=parseList(channelInput.value),r=randomizeCheckbox.checked,i=parseFloat(delayInput.value)||0,l=limitInput.value?parseInt(limitInput.value):Infinity,c=mentionInput.value.trim()?parseList(mentionInput.value):null,d=pollTitleInput.value.trim()||null,u=pollAnswersInput.value.trim()?parseList(pollAnswersInput.value):null,m=parseMessageUrl(n),g=!!m;if(n&&!m)return appendLog("Warning: 無効なURL"),submitBtn.disabled=!1,submitBtn.classList.remove("loading"),void(submitBtn.textContent="RAID START");let p=0;const f=[];g&&o.forEach(t=>{f.push(async()=>{while(!shouldStopSpam&&p<l)for(const e of a){if(await forwardMessageWithRetry(t,e,m))p++;if(p>=l)return void appendLog("Success: 転送完了");if(i)await sleep(i*1000)}})}),e&&o.forEach(t=>{f.push(async()=>{while(!shouldStopSpam&&p<l)for(const e of a){if(await sendMessageWithRetry(t,e,e,{randomize:r,randomMentions:c,pollTitle:d,pollAnswers:u}))p++;if(p>=l)return void appendLog("Success: 送信完了");if(i)await sleep(i*1000)}})}),await Promise.all(f.map(t=>t())),submitBtn.disabled=!1,submitBtn.classList.remove("loading"),submitBtn.textContent="RAID START",appendLog("Success: 完了")};
stopBtn.onclick=()=>{shouldStopSpam=!0;appendLog("Stopped");submitBtn.disabled=!1;submitBtn.classList.remove("loading");submitBtn.textContent="RAID START"};
leaveBtn.onclick=async()=>{shouldStopSpam=!0;appendLog("Exiting...");const t=parseList(tokensInput.value),e=guildInput.value.trim();if(!t.length||!e)return appendLog("Warning: 入力不足");for(const n of t)await leaveGuild(n,e);appendLog("Success: 退出完了");submitBtn.disabled=!1;submitBtn.classList.remove("loading");submitBtn.textContent="RAID START"};
